# Generated by Django 2.0.1 on 2018-06-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_comment_createtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='Commment',
        ),
    ]
